### ISSUE TITLE
failed merge script run for EKKO and EKPO

### ISSUE THREAD

**Issue by mccruz24** [GoogleCloudPlatform/cortex-dag-generator#5]
Hello! 

We checked the pipeline earlier that process the CDC tables for EKKO and EKPO and we noticed that it failed. I tried to run the merge script for both table in BQ and I'm getting an error like below. Not sure if you have encountered this or you have solutions on this. 

ERROR: Too many partitions produced by query, allowed 4000, query produces at least 4001 partitions

Hopefully you can help us with this. 

Thanks!

**Comment by benschuler** [comment]
Hi @mcruzhkm, thanks for reaching out. This error message is a default BigQuery message indicating that your current configuration would exceed the maximum quota of 4000 partitions on a single table. 

Our templates provide some suggestions to help customers get started quickly, but it is expected that you need to make adjustments to our suggested configuration depending on your individual situation. Please consult the official documentation about [how BigQuery handles partitioning](https://cloud.google.com/bigquery/docs/partitioned-tables) and [clustering](https://cloud.google.com/bigquery/docs/clustered-tables) if you'd like to learn more about this topic, or consider working with a partner that can guide you through the process of determining the right settings for your specific scenario.

Best regards,
Benjamin
